version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "8080:80"
    depends_on:
      - backend
