name: CI/CD Pipeline for Dockerized 2-Tier App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: emmanuelsheye/backend:v1

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: emmanuelsheye/frontend:v1

      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          password: ${{ secrets.AZURE_VM_PASS }}
          script: |
            docker pull emmanuelsheye/backend:v1
            docker pull emmanuelsheye/frontend:v1
            docker stop backend_app || true && docker rm backend_app || true
            docker stop frontend_app || true && docker rm frontend_app || true
            docker run -d -p 5000:5000 --name backend_app emmanuelsheye/backend:v1
            docker run -d -p 80:80 --name frontend_app emmanuelsheye/frontend:v1

